### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [dannn98/Projekt-Jezyki-Symboliczne#1]
1. `opis_Gomoku.md` przenieść pod nazwę `README.md`.
2. [Tutaj](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/2471b94e29cdf372be0394122f0f60b34f21318c/mygui.py#L48): z 15 zrobić `BOARD_SIZE`, zamiast `range(97, 112)` użyć `string.ascii_lowercase[:BOARD_SIZE]`, zamiast wygibasów tworzyć listy złożone ze znaków, a odpowiadające kolejnym wierszom planszy, po czym je zamieniać na napisy przez `'\t'.join()` i analogicznie dodawać te napisy do listy, a na koniec użyć `'\n'.join()`.
3. Zamienić nazwy funkcji i zmiennych na `snake_case` (*vide* 2. rozdział Poradnika).
4. [Tutaj](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/2471b94e29cdf372be0394122f0f60b34f21318c/mygame.py#L7) dodać `_EMPTY = '.'`.
5. [Tutaj](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/2471b94e29cdf372be0394122f0f60b34f21318c/mygame.py#L33) nie pisać `97`, tylko `ord('a')`.
6. [Zamiast 5](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/2471b94e29cdf372be0394122f0f60b34f21318c/mygame.py#L55) zrobić nazwaną stałą (2. rozdział).
7. [Zamiast zmiennych `win` i `draw`](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/2471b94e29cdf372be0394122f0f60b34f21318c/mygame.py#L48) zrobić zmienną `game_status`, przyjmującą wartości `GOING_ON, VICTORY, DRAW = range(3)`, a sześć pętli niżej wyjąć do sześciu metod, z których każda zwraca właśnie taki status.
8. W `myexception.py` powyrzucać metody `printMessage()`, za to dodać do klasy `Error`:
```python
def __init__(self, message):
    self._message = message

def __str__(self):
    return self._message
```
oraz dodać jakiś `message` do `GameOverException`. Wtedy klasa `UndefinedException` nie musi mieć żadnych metod, a pozostałe klasy — tylko `__init__()` wołające konstruktor rodzica.
9. Wcięcia w `myexception.py` są niekonsekwentne. Proszę się zaprzyjaźnić z pylintem (2. rozdział).
10. Moduł `main` jest *prawie* dobry (3. rozdział).

**Comment by dannn98** [comment]
Poprawione

**Comment by MarcinCiura** [comment]
Co z `ai_move()`? Z 15 zrobić stałą. Nie zamykać uwag, dopóki nie będzie końca.

**Comment by dannn98** [comment]
Dopisano funkcję ai_move(), implementacja algorytmu minmax, prosta metoda do oceny pozycji, końcowe poprawki

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Projekt wygląda całkiem porządnie. Po uwzględnieniu poniższych uwag będę go mógł zaliczyć.
1. [`< self._BOARD_SIZE`](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/30d3ea79e3e24b4f0cf484fe1fac39871055c022/mygame.py#L44).
2. [`self._BOARD_SIZE - 1`](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/30d3ea79e3e24b4f0cf484fe1fac39871055c022/mygame.py#L66).
3. [To](https://github.com/dannn98/Projekt-Jezyki-Symboliczne/blob/30d3ea79e3e24b4f0cf484fe1fac39871055c022/mygame.py#L518) można uprościć:
```python
except (
    ex.Ex1,
    ex.Ex2,
    ex.Ex3,
    ex.Ex4) as err:
```
4. Na końcu pliku z testami dopisać dwa magiczne wiersze.

**Comment by dannn98** [comment]
Wprowadziłem zalecane przez Pana zmiany. Zamieniłem liczby 14 na self._BOARD_SIZE - 1, poprawiłem kwestię związaną z wyjątkami oraz dodałem dwa magiczne wiersze.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. LGTM.
